version: "0.0.7"

# Enables debug mode
debug: false

# Should loot drop from passive animals?
neutral-mobs-drop: false

# Should loot drop from mobs from spawners?
spawner-mobs-drop: false

# Controls item names floating above dropped loot.
# Disable if you have another plugin for this.
show-item-nameplates: true

# If set to true, tomes drop, and you must use them to
# enchant. Otherwise, it uses vanilla.
custom-enchanting: true

# Should tome enchantments stack? If true, tomes will
# add to current enchantments. If false, tomes will
# only work on items if the tome has a more powerful
# enchantment.
enchantments-stack: true


# Chance that killing an enemy will degrade enchantments
# On word equipment that has them.
enchantment-degrade: 1.0

# Chance that items will have any random upgrade
# value applied on drop.
random-upgrade-quantityBonus: 0.1

# Chance that items will have additional random upgrades
# applied to the drop. This stacks, so 0.1 would
# be 10% quantityBonus of +2, 1% quantityBonus of +3, 0.1% quantityBonus
# of +4, etc.
multi-upgrade-quantityBonus: 0.1

# Chance that items will have a bonus to their
# quality, increasing its base stat
random-quality-quantityBonus: 0.1

# Chance that items will have additional random quality
# ups applied to the drop. This stacks, so 0.1 would
# be 10% quantityBonus of Superior, 1% quantityBonus of Perfect, 0.1%
# quantityBonus of Ultimate, etc.
multi-quality-quantityBonus: 0.1

# How long loot drops assigned to a specific player
# should disallow anyone else to pick it up. The
# assigned player is determiend randomly from the
# list of attackers, with weight based on dmg dealt
loot-protect-time: 10

material-quality-up: 0.05

# Worlds where loot items wlll drop
enabled-worlds:
- main
- yololand


socket-gems:
  use-potion-triggers:  true

crafting:
  base-craft-exp: 1
  craft-item-level-mult: 3
  craft-quality-mult: 0.2
  craft-master-mult: 3.0
  craft-max-quality: 5
  craft-max-craft-slots: 5
  craft-max-sockets: 3
  infusion-base-success-chance: 0.3
  base-infusion-exp: 4
  infusion-exp-per-essence: 2
  infusion-item-level-mult: 0.05
  infusion-success-mult: 2.5

selling:
  base-gem-price: 8
  weight-per-half-gem-price: 100
  base-tome-price: 10
  weight-per-half-tome-price: 100
  base-scroll-price: 1000
  weight-per-half-scroll-price: 100
  base-equipment-price: 6
  equipment-price-per-level: 0.14
  material-prices:
    APPLE: 100
  name-prices:
    "Lesser Upgrade Scroll": 100
    "meme": 100

# Extra drops based on the number of mob mods
mob-mod-bonus:
  1:
    - UNCOMMON
  2:
    - UNCOMMON
    - RARE
  3:
    - RARE
    - EPIC

# Probability that mobs will drop an item of each
# type when it is killed
drops:
  normal-drop: 0.2
  craft-mat: 0.01
  socket-gem: 0.4
  enchant-gem: 0.1
  upgrade-scroll: 0.1
  reveal-powder: 0.1
  identity-tome: 0.01
  junk-item: 0.1
  unique-item: 0.1
  socket-extender: 0.000001
  unidentified-item: 0.1


custom-model-data:
  tier-start-value: 12000
  tier-per-level: 10

# Items that cannot be altered by upgrade scrolls
cannot-be-upgraded:
- Fuck
- This
- Shit