name: Loot
version: ${project.version}
main: info.faceland.loot.LootPlugin
api-version: 1.16
depend:
  - Facecore
softdepend:
  - Strife
  - Vault
  - PlayerPoints
  - InteractiveChatDiscordSrvAddon
  - RecipeManager

commands:
  loot:
    aliases: [l]
  updateItem:
    aliases: [updat]

permissions:
  loot.give:
    default: op
  loot.reward:
    default: op